- hosts: all
  become: true
  pre_tasks:
    - name: update repositories
      state: latest
      apt: 
        name: '*'
        state: latest
        update_cache: yes
      changed_when: False

  tasks:
    - include: tasks/packages.yml
    - include: tasks/users.yml
    - include: tasks/cron.yml
